# Generated by Django 5.0.4 on 2024-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
